Admin/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import login_required, current_user
from models import *
from form import *
from datetime import date
from io import BytesIO
from pyzbar.pyzbar import decode
import qrcode, boto3, os, cv2

admin = Blueprint("admin", __name__)
s3 = boto3.resource(
  "s3",
  aws_access_key_id = os.environ.get("AWS_ACCESS_KEY"),
  aws_secret_access_key = os.environ.get("AWS_SECRET_KEY")
)
client = boto3.client(
  "s3",
  aws_access_key_id = os.environ.get("AWS_ACCESS_KEY"),
  aws_secret_access_key = os.environ.get("AWS_SECRET_KEY")
)
bucket_name = os.environ.get("BUCKET_NAME")
ALLOWED_EXTENSIONS = {"jpg", "jpeg", "png"}

@admin.route("/create-event", methods=["POST", "GET"])
@login_required
def create_event():
  form = EventForm()
  if form.validate_on_submit():
    event = Event.query.filter_by(name=form.name.data, is_active=True).first()
    todays_date = date.today()
    start_date = form.start_date.data
    end_date = form.end_date.data
    if str(start_date) < str(todays_date):
      flash("Start date cannot be before current date", category="danger")
      return redirect(url_for('admin.create_event'))
    elif event:
      flash("An event with that name already exists and it's ongoing", category="danger")
      return redirect(url_for('admin.create_event'))
    elif end_date < start_date:
      flash("End Date cannot be before start date", category="danger")
      return redirect(url_for('admin.create_event'))
    else:
      new_event = Event(
        name = form.name.data,
        tagline = form.tagline.data,
        description = form.description.data,
        start_date = start_date,
        end_date = end_date,
        start_time = form.start_time.data,
        end_time = form.end_time.data,
        location = form.location.data,
        tickets = form.no_of_tickets.data,
        user = current_user.id
      )
      db.session.add(new_event)
      db.session.commit()
      generate_qrcode(new_event.id, new_event.tickets)
      flash(f"Event '{new_event.name}' created successfully", category="success")
      return redirect(url_for('admin.pricing', event_id=new_event.id))
  return render_template("create_event.html", form=form)

@admin.route("/pricing/<int:event_id>", methods=["POST", "GET"])
@login_required
def pricing(event_id):
  try:
    event = Event.query.get(event_id)
    pricing = Pricing.query.filter_by(event=event.id).all()
    form = PricingForm()
    if request.method == "POST":
      if form.validate_on_submit():
        new_pricing = Pricing(
          name = form.name.data,
          amount = form.price.data,
          event = event.id
        )
        db.session.add(new_pricing)
        db.session.commit()
        flash(f"Ticket added for {event.name}", category="success")
        return redirect(url_for('admin.pricing', event_id=event.id))
    return render_template("pricing.html", event=event, form=form, pricing=pricing)
  except:
    flash("An error occurred", category="danger")
    return redirect(url_for('users.home'))

@admin.route("/remove-pricing/<int:event_id>/<int:pricing_id>")
@login_required
def remove_pricing(event_id, pricing_id):
  try:
    event = Event.query.get(event_id)
    if event:
      pricing = Pricing.query.get(pricing_id)
      if pricing:
        db.session.delete(pricing)
        db.session.commit()
        flash("Ticket removed successfully", category="success")
        return redirect(url_for('admin.pricing', event_id=event.id))
    else:
      flash("Event not found", category="danger")
      return redirect(url_for('admin.pricing', event_id=event.id))
  except:
    flash("An error occurred", category="danger")
    return redirect(url_for('users.home'))

@login_required
def generate_qrcode(event_id, tickets):
  event = Event.query.get(event_id)
  if event:
    folder_name = event.name
    for i in range(tickets):
      new_qrcode = Qrcodes(
        event = event_id,
        unique_id = random.randint(100000000,999999999),
        bucket = bucket_name,
        region = os.environ.get("REGION")
      )
      db.session.add(new_qrcode)
      db.session.commit()
      qr = qrcode.QRCode(version=1, box_size=10, border=4)
      qr.make(fit=True)
      qr.add_data(new_qrcode.unique_id)
      img_buffer = BytesIO()
      qr.make_image(fill_color="black", back_color="orange").save(img_buffer)
      img_buffer.seek(0)
      image_name = f"{folder_name}/" + str(new_qrcode.unique_id) + '.png'
      s3.Bucket(bucket_name).upload_fileobj(img_buffer, image_name)

@admin.route('/scan-qrcode/<int:event_id>')
@login_required
def scan_qrcode(event_id):
  event = Event.query.filter_by(unique_id=event_id).first()
  capture = cv2.VideoCapture(0, cv2.CAP_DSHOW)
  received_data = None
  while True:
    _,frame = capture.read()
    decoded_data = decode(frame)
    try:
      data = decoded_data[0][0]
      if data != received_data:
        print(data)
        received_data = data
    except:
      pass
    cv2.imshow("Qr Code Scanner Fram ", frame)
    key = cv2.waitKey(1)
    if key == ord("q"):
      break
  return redirect(url_for('admin.verify_qrcode', event_id=event.unique_id, qrcode=data))

@admin.route('/verify-qrcode/<int:event_id>/<int:qrcode>')
@login_required
def verify_qrcode(event_id, qrcode):
  event = Event.query.filter_by(unique_id=event_id).first()
  qrcode = Qrcodes.query.filter_by(unique_id=qrcode).first()
  if qrcode:
    if qrcode.event != event.id:
      flash("Invalid qrcode for this event", category="danger")
    if qrcode.status != "Assigned":
      flash("Qrcode not valid", category="danger")
    else:
      flash(f"Welcome to {event.name}. Enjoy!", category="success")
  else:
    flash("Unknown Qrcode", category="danger")
  return render_template("qrcode-scan.html", event=event)

@admin.route("/edit-event/<int:event_id>", methods=["POST", "GET"])
@login_required
def edit_event(event_id):
  event = Event.query.filter_by(unique_id=event_id).first()
  if event:
    form = EventForm()
    form.start_time.data = event.start_time
    form.end_time.data = event.end_time
    if request.method == "POST":
      if form.validate_on_submit():
        today_date = date.today()
        if form.start_date.data != event.start_date or form.start_date.data > event.start_date or form.end_date.data < today_date or form.end_date.data < event.start_date:
          if form.start_date.data < today_date or form.end_date.data < today_date or form.end_date.data < event.start_date:
            flash("Invalid date", category="danger")
            return redirect(url_for('admin.edit_event', event_id=event.unique_id))
        event.name = form.name.data
        event.tagline = form.tagline.data
        event.description = form.description.data
        event.start_date = form.start_date.data
        if form.start_date.data > form.end_date.data:
          event.end_date = form.start_date.data
        else:
          event.end_date = form.end_date.data
        event.start_time = form.start_time.data
        event.end_time = form.end_time.data
        event.location = form.location.data
        event.tickets = form.no_of_tickets.data
        db.session.commit()
        flash(f"Event {event.name} updated successfully", category="success")
        return redirect(url_for('users.home'))
      
      if form.errors != {}:
        for err_msg in form.errors.values():
          flash(f"{err_msg}", category="danger")
  else:
    flash("Event not found", category="danger")
    return redirect(url_for('users.home'))
  return render_template("edit_event.html", event=event, form=form)

@admin.route("/delete-event/<int:event_id>")
@login_required
def delete_event(event_id):
  try:
    event = Event.query.filter_by(unique_id=event_id).first()
    qrcodes = Qrcodes.query.filter_by(event=event.id).all()
    pricing = Pricing.query.filter_by(event=event.id).all()
    bookings = Bookings.query.filter_by(event=event.id).all()
    for qrcode in qrcodes:
      db.session.delete(qrcode)
    for ticket in pricing:
      db.session.delete(ticket)
    for booking in bookings:
      db.session.delete(booking)
    db.session.delete(event)
    db.session.commit()
    flash(f"Event {event.name} has been removed successfully", category="success")
  except:
    flash("An error occured", category="danger")
  return redirect(url_for('users.home'))

Users/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, request
from flask_login import login_required, current_user
from models import *
from form import *
from datetime import datetime, date
import stripe, os

users = Blueprint("users", __name__)
stripe.api_key = os.environ.get("Stripe_api_key")

@users.before_request
def event_expiry():
  all_events = Event.query.all()
  for event in all_events:
    today = date.today()
    current_time = datetime.now()
    if event.end_date < today:
      event.is_ended = True
      event.is_active = False
      qrcodes = Qrcodes.query.filter_by(event=event.id).all()
      for qrcode in qrcodes:
        qrcode.status = "Closed"
        db.session.commit()
    if event.tickets < 1:
      event.is_soldout = True
    db.session.commit()
  return None

@users.route("/")
@users.route("/home")
@login_required
def home():
  events = Event.query.all()
  ticket_pricing = Pricing.query.all()
  today = date.today()
  current_time = datetime.now()
  return render_template("index.html", events=events, today=today, current_time=current_time, ticket_pricing=ticket_pricing)

@users.route("/event-details/<int:event_id>")
def event_details(event_id):
  try:
    event = Event.query.get(event_id)
    if event:
      pricing = Pricing.query.filter_by(event=event.id).all()
      return render_template("event.html", event=event, pricing=pricing)
    else:
      flash("Event not found", category="danger")
      return redirect(url_for('users.home'))
  except:
    flash("An error ocurred", category="danger")
    return redirect(url_for('users.home'))

@users.route("/tickets/<int:event_id>", methods=["POST", "GET"])
@login_required
def tickets(event_id):
  event = Event.query.get(event_id)
  form = TicketForm()
  form.ticket.choices = [(ticket.id, f"{ticket.name} - Ksh {'{:,}'.format(ticket.amount)}") for ticket in Pricing.query.filter_by(event=event.id).all()]
  if event:
    if form.validate_on_submit():
      if int(request.form.get("tickets")) > event.tickets:
        flash(f"Only {event.tickets} tickets are available", category="info")
        return redirect(url_for('users.tickets', event_id=event.id))
      if current_user.is_authenticated:
        new_booking = Bookings(
          user = current_user.id,
          event = event.id,
          ticket = form.ticket.data,
          tickets = form.tickets.data
        )
        db.session.add(new_booking)
        event.tickets = event.tickets - int(new_booking.tickets)
        db.session.commit()
        pricing = Pricing.query.filter_by(id=new_booking.ticket).first()
        new_booking.total = pricing.amount * int(new_booking.tickets)
        db.session.commit()
        for i in range(new_booking.tickets):
          qrcode = Qrcodes.query.filter_by(event=event.id, status="Active").first()
          qrcode.booking = new_booking.id
          qrcode.status = "Assigned"
          db.session.commit()
        # return redirect(url_for('users.payment', booking_id=new_booking.id))
        flash("Your tickets are ready", category="success")
        return redirect(url_for('users.home'))
      else:
        new_user = Users(
          first_name = form.first_name.data,
          surname = form.last_name.data,
          email = form.email.data,
          phone = form.phone_number.data,
        )
        db.session.add(new_user)
        db.session.commit()
        new_booking = Bookings(
          user = new_user.id,
          event = event.id,
          ticket = form.ticket.data,
          tickets = form.tickets.data
        )
        db.session.add(new_booking)
        event.tickets = event.tickets - new_booking.tickets
        db.session.commit()
        pricing = Pricing.query.filter_by(id=new_booking.ticket).first()
        new_booking.total = pricing.amount * int(new_booking.tickets)
        db.session.commit()
        flash("Your tickets are ready", category="success")
        return redirect(url_for('users.home'))

    if form.errors != {}:
      for err_msg in form.errors.values():
        flash(f"{err_msg}", category="danger")
  else:
    flash("Event could not be found", category="danger")
    return redirect(url_for('users.home'))
  return render_template("book.html", event=event, form=form)

@users.route("/payment/<int:booking_id>")
@login_required
def payment(booking_id):
  booking = Bookings.query.get(booking_id)
  event = Event.query.get(booking.event)
  total = event.price * booking.tickets
  try:
    checkout_session = stripe.checkout.Session.create(
      line_items = [
        {
          'price_data': {
            'currency': 'KES',
            'product_data': {
              'name': f"{event.name}'s tickets",
            },
            'unit_amount': (total*100),
          },
          'quantity': 1,
        }
      ],
      payment_method_types=["card"],
      mode='payment',
      success_url=request.host_url + f'payment-complete/{booking.id}',
      cancel_url=request.host_url + f'payment-failed/{booking.id}',
    )
    return redirect(checkout_session.url)
  except:
    event.tickets = event.tickets + booking.tickets
    db.session.delete(booking)
    db.session.commit()
    flash(f"Failed to initialize connection to the stripe server", category="warning")
    return redirect(url_for('users.home'))

@users.route("/payment-complete/<int:booking_id>")
@login_required
def payment_complete(booking_id):
  booking = Bookings.query.get(booking_id)
  booking.status = "Complete"
  db.session.commit()
  flash("Payment successfull, your tickets are ready", category="success")
  return redirect(url_for('users.home'))

@users.route("/payment-failed/<int:booking_id>")
@login_required
def payment_failed(booking_id):
  booking = Bookings.query.get(booking_id)
  event = Event.query.get(booking.event)
  event.tickets = event.tickets + booking.tickets
  db.session.delete(booking)
  db.session.commit()
  flash("Payment failed", category="danger")
  return redirect(url_for('users.home'))

@users.route("/orders")
def orders():
  bookings = Bookings.query.filter_by(user=current_user.id).all()
  qrcodes = Qrcodes.query.all()
  return render_template("orders.html", bookings=bookings, qrcodes=qrcodes)

templates/event.html
{% extends "layout.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="../static/css/event.css">
{% endblock %}

{% block title %}
{{ event.name }}
{% endblock %}

{% block body %}
<div class="container">
  <div class="event-header">
    <div class="event-header-info">
      <h1>{{ event.name }}</h1>
      <h4>{{ event.tagline }}</h4>
    </div>
    <div class="header-actions">
      <a href="{{ url_for('admin.scan_qrcode', event_id=event.unique_id) }}">Admit</a>
    </div>
  </div>
  <div class="event-box">
    <div class="event-description">
      <h1>Event Description</h1>
      <p>{{ event.description }}</p>
    </div>
    <div class="event-details">
      <h1>Event Details</h1>
      <div class="event-details-info">
        <div class="event-location">
          <h3>Location</h3>
          <p>{{ event.location }}</p>
        </div>
        <div class="event-dates">
          <p>Start Date: <b>{{ event.start_date.strftime("%d/%m/%Y") }}</b></p>
          <p>End Date: <b>{{ event.end_date.strftime("%d/%m/%Y") }}</b></p>
          <p>Start Time: <b>{{ event.start_time.strftime("%I:%M %p") }}</b></p>
          <p>End Time: <b>{{ event.end_time.strftime("%I:%M %p") }}</b></p>
        </div>
        <div class="event-tickets">
          <h3>Event Tickets</h3>
          <div class="event-tickets-box">
            {% for price in pricing %}
            <div class="ticket">
              <h4>{{ price.name }}</h4>
              <p>{{ "Ksh {:,}".format(price.amount) }}</p>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="event-actions">
          <div class="tickets-btn">
            {% if event.is_soldout == True %}
            <button disabled>
              <img src="{{ url_for('static', filename='Images/tickets.png') }}" alt="Edit Event">
              Sold Out
            </button>
            {% elif event.is_ended == True %}
            <button disabled="disabled">
              <img src="{{ url_for('static', filename='Images/tickets.png') }}" alt="Edit Event">
              Ended
            </button>
            {% else %}
            <a href="{{ url_for('users.tickets', event_id=event.id) }}">
              <button>
                <img src="{{ url_for('static', filename='Images/tickets.png') }}" alt="Edit Event">
                Buy Ticket
              </button>
            </a>
            {% endif %}
          </div>
          {% if event.user == current_user.id %}
          <div class="edit-btns">
            <a href="{{ url_for('admin.edit_event', event_id=event.unique_id) }}">
              <img src="../static/images/editing.png" alt="">
            </a>
            <a href="{{ url_for('admin.delete_event', event_id=event.unique_id) }}">
              <img src="../static/images/delete.png" alt="">
            </a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="../static/js/auth.js"></script>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="../static/css/style.css">
{% endblock %}

{% block title %}
Home
{% endblock %}

{% block body %}
<div class="events">
  <div class="menu-box">
    <div class="menu-items">
      <div id="defaultOpen" class="img-box tablinks" onclick="openView(event, 'upcoming')">
        <img src="{{ url_for('static', filename='images/upcoming.png') }}" alt="upcoming event">
      </div>
      <div class="line"></div>
      <div class="img-box tablinks" onclick="openView(event, 'past')">
        <img src="{{ url_for('static', filename='images/past.png') }}" alt="upcoming event">
      </div>
    </div>
    {% if current_user.role == 1 %}
    <a id="event-link" href="{{ url_for('admin.create_event') }}">Create Event</a>
    {% endif %}
  </div>
  <div class="all-events">
    <div id="upcoming" class="tabcontent">
      <h1 id="header">Upcoming Events</h1>
      <div class="events-box">
        {% set upcoming_events = [] %}
        {% for event in events if event.is_active == True or (event.is_active == True and event.is_soldout == True) %}
        {{ upcoming_events.append(event) or "" }}
        {% endfor %}
        {% if upcoming_events %}
        {% for event in upcoming_events|sort(attribute='start_date') %}
        <div class="event">
          <div class="image-box">
            <img src="../static/images/banner.png" alt="event-img">
          </div>
          <div class="box">
            <a href="{{ url_for('users.event_details', event_id=event.id) }}">
              <div class="event-info">
                <div class="event-header">
                  <h1>{{ event.name }}</h1>
                  {% if (event.start_date < today and event.start_time.strftime("%H:%M") <
                    current_time.strftime("%H:%M")) or (event.start_date==today and event.start_time.strftime("%H:%M") <
                    current_time.strftime("%H:%M")) %} <p class="ongoing">
                    Ongoing
                    <span id="ongoing">.</span>
                    <span id="ongoing">.</span>
                    <span id="ongoing">.</span>
                    </p>
                    {% endif %}
                </div>
                <p class="event-loc">
                  Location: {{ event.location }}
                  {% if event.tickets
                  < 10 and event.is_soldout !=True %} <span id="selling-out">Almost selling out</span>
                    {% endif %}
                </p>
                <div class="event-dates">
                  <p>Start Date: <b>{{ event.start_date.strftime("%d/%m/%Y") }}</b></p>
                  <p>End Date: <b>{{ event.end_date.strftime("%d/%m/%Y") }}</b></p>
                  <p>Start Time: <b>{{ event.start_time.strftime("%I:%M %p") }}</b></p>
                  <p>End Time: <b>{{ event.end_time.strftime("%I:%M %p") }}</b></p>
                </div>
                <hr>
                <div class="tickets-box">
                  <div class="tickets-price">
                    <img src="../static/images/voucher.png" alt="ticket">
                    {% set pricing = [] %}
                    {% for price in ticket_pricing if price.event == event.id %}
                    {{ pricing.append(price) or "" }}
                    {% endfor %}
                    {% if pricing|count > 1 %}
                    <span id="multiple">Multiple Tickets</span>
                    {% else %}
                    <h4>
                      {% for ticket in pricing %}
                      {{ "Ksh {:,}".format(ticket.amount) }}
                      {% endfor %}
                    </h4>
                    {% endif %}
                  </div>
                  <div class="tickets">
                    {% if event.is_soldout == True %}
                    <button disabled>
                      <img src="{{ url_for('static', filename='Images/tickets.png') }}" alt="Edit Event">
                      Sold Out
                    </button>
                    {% elif event.is_ended == True %}
                    <button disabled="disabled">
                      <img src="{{ url_for('static', filename='Images/tickets.png') }}" alt="Edit Event">
                      Ended
                    </button>
                    {% else %}
                    <a href="{{ url_for('users.tickets', event_id=event.id) }}">
                      <button>
                        <img src="{{ url_for('static', filename='Images/tickets.png') }}" alt="Edit Event">
                        Buy Ticket
                      </button>
                    </a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <p id="no-events">No Upcoming Events</p>
        {% endif %}
      </div>
    </div>
    <div id="past" class="tabcontent">
      <h1 id="header">Past Events</h1>
      <div class="events-box">
        {% set past_events = [] %}
        {% for event in events if event.is_ended == true %}
        {{ past_events.append(event) or "" }}
        {% endfor %}
        {% if past_events %}
        {% for event in past_events|sort(attribute='start_date') %}
        <div class="event">
          <div class="image-box">
            <img src="../static/images/banner.png" alt="event-img">
          </div>
          <div class="box">
            <a href="{{ url_for('users.event_details', event_id=event.id) }}">
              <div class="event-info">
                <div class="event-header">
                  <h1>{{ event.name }}</h1>
                </div>
                <p class="event-loc">
                  Location: {{ event.location }}
                </p>
                <div class="event-dates">
                  <p>Start Date: <b>{{ event.start_date.strftime("%d/%m/%Y") }}</b></p>
                  <p>End Date: <b>{{ event.end_date.strftime("%d/%m/%Y") }}</b></p>
                  <p>Start Time: <b>{{ event.start_time.strftime("%I:%M %p") }}</b></p>
                  <p>End Time: <b>{{ event.end_time.strftime("%I:%M %p") }}</b></p>
                </div>
                <hr>
                <div class="tickets-box">
                  <div class="tickets-price">
                    <img src="../static/images/voucher.png" alt="ticket">
                    {% set pricing = [] %}
                    {% for price in ticket_pricing if price.event == event.id %}
                    {{ pricing.append(price) or "" }}
                    {% endfor %}
                    {% if pricing|count > 1 %}
                    <span id="multiple">Multiple Tickets</span>
                    {% else %}
                    <h4>
                      {% for ticket in pricing %}
                      {{ "Ksh {:,}".format(ticket.amount) }}
                      {% endfor %}
                    </h4>
                    {% endif %}
                  </div>
                  <div class="tickets">
                    {% if event.is_ended == True %}
                    <button disabled id="tickets">
                      <img src="{{ url_for('static', filename='Images/tickets.png') }}" alt="Edit Event">
                      Ended
                    </button>
                    {% endif %}
                  </div>
                </div>
              </div>
          </div>
          </a>
        </div>
      </div>
      {% endfor %}
      {% else %}
      <p id="no-events">No Past Events</p>
      {% endif %}
    </div>
  </div>
</div>
</div>

<script src="{{ url_for('static', filename='js/index.js') }}"></script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

{% block head %}

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="../static/css/layout.css">
  <link rel="shortcut icon" href="../static/images/favicon.png" type="image/x-icon">
  <title>SOF Tickets | {% block title %}{% endblock %}</title>
</head>
{% endblock %}

<header>
  <a href="{{ url_for('users.home') }}">
    <img id="logo" src="../static/images/Screenshot.png" alt="sofafrica.com logo">
  </a>
  <div class="links-box">
    {% if current_user.is_authenticated %}
    <div class="account">
      <div class="account-info">
        <p>{{ current_user.user_role.role_name }}</p>
        <img src="../static/images/profile.png" alt="user-profile">
      </div>
      <div class="bookings">
        <div class="booking">
          <a href="#">
            <p>Profile</p>
          </a>
          <a href="{{ url_for('users.orders') }}">
            <p> My Tickects</p>
          </a>
          {% if current_user.role == 1 %}
          <a href="#">
            <p> My Events</p>
          </a>
          {% endif %}
          <a href="{{ url_for('auth.logout') }}">
            <p id="logout">Logout</p>
          </a>
        </div>
      </div>
    </div>
    {% else %}
    <div class="links">
      <a id="link" href="{{ url_for('auth.signup') }}">Sign Up</a>
      <a id="link" href="{{ url_for('auth.signin') }}">Sign In</a>
    </div>
    {% endif %}
  </div>
  <div class="burger">
    <div class="div"></div>
    <div class="div"></div>
    <div class="div"></div>
  </div>
</header>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="tops">
  {% for category, message in messages %}
  <div class="alert alert-{{category}}">
    {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% endwith %}

<body>
  {% block body %}
  {% endblock %}
</body>

{% block script %}
{% endblock %}
<script src="{{ url_for('static', filename='js/layout.js') }}"></script>

</html>

templates/login.html
{% extends 'layout.html' %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/register.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
{% endblock %}

{% block title %}
Login
{% endblock %}

{% block body %}
<div class="form">
  <h4>Sign In</h4>
  <form id="form" method="post">
    {{ form.csrf_token }}
    <div class="input">
      {{ form.email_address.label }}
      {{ form.email_address(placeholder="Enter Email Address", class="name") }}
    </div>
    <div class="input">
      {{ form.password.label }}
      {{ form.password(placeholder="Enter Password", class="name") }}
    </div>
    <button class="btn" type="submit">
      <span class="button--text">SIGN IN</span>
    </button>
    <span id="info">Don't have an account? <a href="{{ url_for('auth.register') }}">Sign Up</a></span>
  </form>
</div>

<script src="{{ url_for('static', filename='js/auth.js') }}"></script>
{% endblock %}

templates/pricing.html
{% extends "layout.html" %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="../static/css/pricing.css">
{% endblock %}

{% block title %}
{{ event.name }}
{% endblock %}

{% block body %}
<div class="pricing">
  <h1>{{ event.name }}</h1>
  <p>Enter your various ticket prices</p>
  <div class="pricing-box">
    {% if pricing %}
    <div class="pricing-details">
      <div class="pricing-info">
        {% for ticket in pricing %}
        <div class="ticket">
          <div class="ticket-info">
            <h4>{{ ticket.name }}</h4>
            <p>{{ "Ksh {:,}".format(ticket.amount) }}</p>
          </div>
          <div class="ticket-actions">
            <a href="{{ url_for('admin.remove_pricing', event_id=event.id, pricing_id=ticket.id) }}">
              <img src="../static/images/delete.png" alt="Edit Event">
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    <div class="pricing-form">
      <form method="post">
        {{ form.csrf_token }}
        <div class="input extend">
          {{ form.name.label }}
          {{ form.name(placeholder="Ticket Name", class="name") }}
        </div>
        <div class="input extend">
          {{ form.price.label }}
          {{ form.price(placeholder="Ticket Price", class="name") }}
        </div>
        <button class="btn extend" type="submit">
          <span class="button--text">Add Ticket</span>
        </button>
      </form>
      {% if pricing %}
      <div class="complete">
        <a id="complete" href="{{ url_for('users.home') }}">
          <button>
            Complete
          </button>
        </a>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script src="{{ url_for('static', filename='js/auth.js') }}"></script>
{% endblock %}